/**
 * Regenerates src/generated/plugin-assembly.ts from the compiled NameBuilder
 * Dataverse plugin DLL. Run this after rebuilding NameBuilderPlugin so the
 * tool ships (and installs) the current plugin build.
 *
 * Usage: node scripts/embed-plugin.mjs [path-to-NameBuilder.dll]
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

const dllPath =
  process.argv[2] ??
  path.resolve(here, '..', '..', 'NameBuilderConfigurator', 'Assets', 'DataversePlugin', 'NameBuilder.dll');

if (!fs.existsSync(dllPath)) {
  console.error(`Plugin DLL not found: ${dllPath}`);
  process.exit(1);
}

const bytes = fs.readFileSync(dllPath);
const base64 = bytes.toString('base64');
const sha256 = crypto.createHash('sha256').update(bytes).digest('hex');

/**
 * Extract the assembly version and public key token from the .NET DLL.
 * The version lives in the assembly definition table; rather than write a full
 * PE/CLI metadata parser we look for the well-known attribute text. To keep it
 * reliable, the values may also be passed explicitly:
 *   node scripts/embed-plugin.mjs <dll> <version> <publicKeyToken>
 */
const version = process.argv[3] ?? readVersionFromSiblingBuild() ?? '1.0.0.0';
const publicKeyToken = process.argv[4] ?? 'd3dc72745a5fddc3';

function readVersionFromSiblingBuild() {
  // AssemblyInfo.cs in the plugin project is the source of truth for version.
  const assemblyInfo = path.resolve(here, '..', '..', 'NameBuilderPlugin', 'Properties', 'AssemblyInfo.cs');
  if (!fs.existsSync(assemblyInfo)) return undefined;
  const text = fs.readFileSync(assemblyInfo, 'utf8');
  const match = text.match(/AssemblyVersion\("([^"]+)"\)/);
  return match?.[1];
}

const out = `// AUTO-GENERATED by scripts/embed-plugin.mjs — do not edit by hand.
// Source DLL: ${path.basename(dllPath)} (${bytes.length} bytes)
// Regenerate with: npm run embed-plugin

export const PLUGIN_ASSEMBLY_NAME = 'NameBuilder';
export const PLUGIN_TYPE_NAME = 'NameBuilder.NameBuilderPlugin';
export const PLUGIN_ASSEMBLY_VERSION = '${version}';
export const PLUGIN_PUBLIC_KEY_TOKEN = '${publicKeyToken}';
export const PLUGIN_ASSEMBLY_SHA256 = '${sha256}';
export const PLUGIN_ASSEMBLY_BASE64 =
  '${base64}';
`;

const outPath = path.resolve(here, '..', 'src', 'generated', 'plugin-assembly.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out, 'utf8');
console.log(`Wrote ${outPath}`);
console.log(`  version=${version} pkt=${publicKeyToken} sha256=${sha256.slice(0, 12)}… bytes=${bytes.length}`);
